services:
    daterange.validator:
        class: ScoutEvent\DataBundle\Validator\Constraints\DateRangeValidator
        tags:
            - { name: validator.constraint_validator, alias: daterange_validator }
